get_date_button_show:
  # 获取dateButton是否显示
  -
    # 入参
    configKey: ""
    # 校验接口返回
    code: 200
    # 查询数据库用来校验接口返回的数据
    execute_sql: [
      "select distinct create_time  from `hk-manhattan`.chain_daily_stats order by create_time asc limit 1",
      "select distinct create_time  from `hk-manhattan`.chain_collection_quotation order by create_time asc limit 1"
    ]
  -
    configKey: "MARKET_CAP_VOLUME"
    code: 200
    execute_sql: [
      "select distinct create_time  from `hk-manhattan`.chain_collection_quotation order by create_time asc limit 1"
    ]
  -
    configKey: "PRICE_LIST"
    code: 200
    execute_sql: [
      "select distinct create_time  from `hk-manhattan`.chain_collection_quotation order by create_time asc limit 1"
    ]
  -
    configKey: "TOP_TEN"
    code: 200
    execute_sql: [
      "select distinct create_time  from `hk-manhattan`.chain_collection_quotation order by create_time asc limit 1"
    ]
  -
    configKey: "ETHEREUM"
    code: 200
    execute_sql: [
      "select distinct create_time  from `hk-manhattan`.chain_daily_stats order by create_time asc limit 1"
    ]
  -
    configKey: "TOP_SALES"
    code: 200
    execute_sql: [
      "select distinct create_time  from `hk-manhattan`.chain_collection_quotation order by create_time asc limit 1"
    ]
  -
    configKey: "TOP_COLLECTION"
    code: 200
    execute_sql: [
      "select distinct create_time  from `hk-manhattan`.chain_collection_quotation order by create_time asc limit 1"
    ]
  -
    configKey: "HOT_COLLECTION"
    code: 200
    execute_sql: [
      "select distinct create_time  from `hk-manhattan`.chain_collection_quotation order by create_time asc limit 1"
    ]
  -
    configKey: "TRANSACTION_COUNT"
    code: 200
    execute_sql: [
      "select distinct create_time  from `hk-manhattan`.chain_daily_stats order by create_time asc limit 1"
    ]

check_version_update:
  -
    # 校验接口返回的对应的字段
    code: 200
    version: equal_now_force_version
    terminalType: IOS
    forceUpdate: False
  -
    code: 200
    version: above_now_force_version
    terminalType: IOS
    forceUpdate: False
  - code: 200
    version: equal_now_update_version
    terminalType: IOS
    needUpdate: False
  - code: 200
    version: above_now_update_version
    terminalType: IOS
    needUpdate: False
  -
    code: 200
    version: below_now_force_version
    terminalType: IOS
    forceUpdate: True
  -
    code: 200
    version: below_now_update_version
    terminalType: IOS
    needUpdate: True
  - code: 200
    version: equal_now_force_version
    terminalType: AND
    forceUpdate: False
  - code: 200
    version: above_now_force_version
    terminalType: AND
    forceUpdate: False
  - code: 200
    version: equal_now_update_version
    terminalType: AND
    needUpdate: False
  - code: 200
    version: above_now_update_version
    terminalType: AND
    needUpdate: False
  - code: 200
    version: below_now_update_version
    terminalType: AND
    needUpdate: True
  - code: 200
    version: below_now_force_version
    terminalType: AND
    forceUpdate: True